---
- name: stop fhem
  service: name=fhem state=stopped
  become: true

- template: 
    src:   fhem.cfg.j2
    dest:  /opt/fhem/fhem.cfg
    owner: fhem
    group: dialout
    mode:  0644

- name: start fhem
  service: name=fhem state=started
  become: true

